### ISSUE TITLE
Don't use cluster-admin for job serviceaccounts

### ISSUE THREAD

**Issue by stevekuznetsov** [redhat-cop/openshift-management#7]
The `cluster-admin` role is not the appropriate role to grant the serviceaccount doing image pruning or LDAP sync/prune. It's overly broad and we should not be suggesting that customers give `cluster-admin` role to anything.

I think the LDAP group sync serviceaccount will need:

```yml
apiVersion: v1
kind: ClusterRole
metadata:
  name: ldap-group-syncer
rules:
  - apiGroups:
      - ""
    resources:
      - groups
    verbs:
      - get
      - list
      - create
      - update
```

The prune serviceaccount will also need to be able to delete groups:

```yaml
apiVersion: v1
kind: ClusterRole
metadata:
  name: ldap-group-pruner
rules:
  - apiGroups:
      - ""
    resources:
      - groups
    verbs:
      - get
      - list
      - create
      - update
      - delete
```

As you're assuming that these jobs are being deployed by an admin, you can have a template with the serviceaccount, role and rolebinding all in one as well:

```yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ldap-group-syncer

apiVersion: v1
kind: RoleBinding
metadata:
  name: ldap-group-syncer
roleRef:
  name: ldap-group-syncer
subjects:
- kind: ServiceAccount
  name: ldap-group-syncer
groupNames: null
```
